# Generated by Django 5.1 on 2024-11-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PID', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('user_id', models.CharField(default='Null', max_length=255)),
                ('user_name', models.CharField(default='Null', max_length=255)),
                ('Predection', models.CharField(default='None', max_length=255)),
            ],
        ),
    ]
