# Generated by Django 5.1 on 2024-11-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='PID',
            new_name='id',
        ),
    ]
