# Generated by Django 5.1 on 2024-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage1', '0002_rename_pid_patients_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='PID',
            field=models.CharField(default='P_00000', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
