# Generated by Django 5.1 on 2024-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage1', '0003_patients_pid_alter_patients_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='PID',
        ),
        migrations.AlterField(
            model_name='patients',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
