# Generated by Django 5.1 on 2024-10-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage1', '0003_remove_patients_id_patients_name_alter_patients_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patients',
            name='PID',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
