# Generated by Django 5.1 on 2024-10-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage1', '0007_alter_userexerciseprogress_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cognitiveexercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cognitiveexercise',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
