# Generated by Django 5.1 on 2024-10-19 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='ADL',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patients',
            name='BehavioralProblems',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='CholestrolHDL',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='CholestrolTotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='Disorientation',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='FunctionalAssessment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='patients',
            name='Hypertension',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='MSME',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='MemoryComplaints',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='PersonalityChanges',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name='patients',
            name='Smoking',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AddField(
            model_name="patients",
            name="PID",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
