# Generated by Django 5.1 on 2024-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage1', '0007_alter_userexerciseprogress_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cognitiveexercise',
            name='id',
        ),
        migrations.AddField(
            model_name='cognitiveexercise',
            name='key',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
