# Generated by Django 5.1 on 2024-10-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage1', '0011_alter_patients_predection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
